runtime:
  cache_dir: ./.cache/antora

site:
  title: Vote App Lab Guides
  start_page: vote-app-guides:m1:intro.adoc

content:
  sources:
    - url: .
      start_path: docs

asciidoc:
  attributes:
    experimental: true
    page-pagination: true

ui:
  bundle:
    url: ./ui/ui-bundle.zip
  supplemental_files: ./ui/supplemental-ui

output:
  dir: ./site
